// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"./login","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/login","layout":false,"id":"2"},"3":{"name":"Dashboard","path":"/dashboard","icon":"DashboardOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"Home","path":"/home","icon":"HomeOutlined","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"Inventory","path":"/inventory","icon":"InventoryOutlined","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"Logout","path":"/logout","icon":"LogoutOutlined","parentId":"ant-design-pro-layout","id":"6"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'6': React.lazy(() => import('./EmptyRoute')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/Personal/Project/the-giftify/web-ui/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
