# Generated by Django 6.1 on 2026-08-17 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RESTOCK', 'Restock Intake'), ('SALE', 'POS Sale Deduction'), ('ADJUSTMENT', 'Manual Inventory Adjustment'), ('RETURN', 'Customer Return')], default='RESTOCK', max_length=20)),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sub_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'db_table': 'tbl_inventory',
                'ordering': ['-created_at'],
            },
        ),
    ]
