# Generated by Django 5.2.17 on 2026-08-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='user.company'),
        ),
    ]
