# Generated by Django 5.0.10 on 2025-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ItCode', models.CharField(max_length=25)),
                ('Unit', models.CharField(max_length=25)),
                ('Qty', models.CharField(max_length=25)),
                ('UnitPrice', models.CharField(max_length=25)),
                ('TotalPrice', models.CharField(max_length=25)),
                ('StockInDate', models.DateTimeField(auto_now_add=True)),
                ('Remarks', models.CharField(max_length=255)),
                ('CreatedBy', models.IntegerField(null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedBy', models.IntegerField(null=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('Status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_ItembalanceIn',
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ItCode', models.CharField(max_length=25)),
                ('Unit', models.CharField(max_length=25)),
                ('Qty', models.CharField(max_length=25)),
                ('UnitPrice', models.CharField(max_length=25)),
                ('TotalPrice', models.CharField(max_length=25)),
                ('StockOutDate', models.DateTimeField(auto_now_add=True)),
                ('Remarks', models.CharField(max_length=255)),
                ('CreatedBy', models.IntegerField(null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedBy', models.IntegerField(null=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('Status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_ItembalanceOut',
            },
        ),
    ]
