# Generated by Django 5.0.10 on 2025-01-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockIn',
        ),
    ]
