# Generated by Django 5.0.10 on 2025-01-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_stockin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='ModifiedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='Remarks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='StockInDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
