# Generated by Django 5.2.17 on 2026-08-22 09:55

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_company_product_company_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=products.models.product_image_upload_path),
        ),
    ]
