# Generated by Django 5.2.17 on 2026-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Color variant e.g. Pink, Red, Blue, Gold', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Size/Spec variant e.g. Giant 80cm, Medium, XL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(default='Pcs', help_text='Unit of Measure e.g. Pcs, Box, Set, Pack, Dozen', max_length=50),
        ),
    ]
