// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from 'D:/Personal/Project/the-giftify/web-ui/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import HomeOutlined from 'D:/Personal/Project/the-giftify/web-ui/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import LogoutOutlined from 'D:/Personal/Project/the-giftify/web-ui/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/LogoutOutlined';
export default { DashboardOutlined, HomeOutlined, LogoutOutlined };
