# Generated by Django 5.2.17 on 2026-08-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('user', '0002_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='user.company'),
        ),
    ]
