# Generated by Django 5.2.17 on 2026-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleorder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
