# Generated by Django 5.2.17 on 2026-08-20 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook Page'), ('telegram', 'Telegram Group/Channel'), ('tiktok', 'TikTok Account')], max_length=20)),
                ('name', models.CharField(help_text='Account/Channel Name', max_length=255)),
                ('app_id_or_bot_token', models.CharField(blank=True, help_text='App ID / Bot Token', max_length=500, null=True)),
                ('page_id_or_chat_id', models.CharField(blank=True, help_text='Facebook Page ID / Telegram Chat ID / TikTok User ID', max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, help_text='OAuth / Page Access Token', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_simulated', models.BooleanField(default=False, help_text='If True, simulates API responses for testing without sending real network calls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'tbl_social_accounts',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Post body / caption')),
                ('image_url', models.CharField(blank=True, help_text='Image file path or URL', max_length=1000, null=True)),
                ('video_url', models.CharField(blank=True, help_text='Video file path or URL', max_length=1000, null=True)),
                ('platforms', models.JSONField(default=list, help_text='Array of target platform names')),
                ('schedule_type', models.CharField(choices=[('IMMEDIATE', 'Publish Immediately'), ('ONE_TIME', 'One-time Scheduled'), ('DAILY_RECURRING', 'Daily Recurring ("Set 1 time, work forever")')], default='IMMEDIATE', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='For ONE_TIME scheduled posts', null=True)),
                ('daily_time', models.TimeField(blank=True, help_text='For DAILY_RECURRING posts e.g. 09:00:00', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='If false, auto-posting scheduler ignores this post')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed / Error')], default='DRAFT', max_length=20)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_social_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='social_publisher.socialpost')),
            ],
            options={
                'db_table': 'tbl_social_post_logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
