# Generated by Django 5.2.17 on 2026-08-20 14:46

import social_publisher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='fb_post_type',
            field=models.CharField(choices=[('FEED', 'Facebook Post / Photo Feed'), ('REEL', 'Facebook Reel (Video)'), ('STORY', 'Facebook Story')], default='FEED', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='image_file',
            field=models.FileField(blank=True, help_text='Uploaded image file', null=True, upload_to=social_publisher.models.social_media_upload_path),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='telegram_post_type',
            field=models.CharField(choices=[('PHOTO', 'Telegram Photo'), ('VIDEO', 'Telegram Video'), ('TEXT', 'Telegram Text Message')], default='PHOTO', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='tiktok_post_type',
            field=models.CharField(choices=[('VIDEO', 'TikTok Video'), ('PHOTO_CAROUSEL', 'TikTok Photo Slideshow')], default='VIDEO', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded video file', null=True, upload_to=social_publisher.models.social_media_upload_path),
        ),
    ]
