# Generated by Django 5.2.17 on 2026-08-20 14:52

import django.db.models.deletion
import social_publisher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publisher', '0002_socialpost_fb_post_type_socialpost_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='image_file',
            field=models.FileField(blank=True, help_text='Primary image file', null=True, upload_to=social_publisher.models.social_media_upload_path),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='image_url',
            field=models.CharField(blank=True, help_text='Primary image URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='video_file',
            field=models.FileField(blank=True, help_text='Primary video file', null=True, upload_to=social_publisher.models.social_media_upload_path),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='video_url',
            field=models.CharField(blank=True, help_text='Primary video URL', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='SocialPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=social_publisher.models.social_media_upload_path)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='social_publisher.socialpost')),
            ],
            options={
                'db_table': 'tbl_social_post_attachments',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
