# Generated by Django 5.2.17 on 2026-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publisher', '0003_alter_socialpost_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='recurring_days',
            field=models.JSONField(blank=True, default=list, help_text='Selected days for WEEKLY_RECURRING e.g. ["MON", "WED", "FRI"]', null=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='daily_time',
            field=models.TimeField(blank=True, help_text='For DAILY_RECURRING & WEEKLY_RECURRING posts e.g. 09:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='schedule_type',
            field=models.CharField(choices=[('IMMEDIATE', 'Publish Immediately'), ('ONE_TIME', 'One-time Scheduled'), ('DAILY_RECURRING', 'Daily Recurring ("Set 1 time, work forever")'), ('WEEKLY_RECURRING', 'Weekly Recurring Days ("Mon, Tue, Wed...")')], default='IMMEDIATE', max_length=20),
        ),
    ]
