# Generated by Django 5.2.17 on 2026-08-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publisher', '0004_socialpost_recurring_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='account_ids',
            field=models.JSONField(blank=True, default=list, help_text='Array of target SocialAccount IDs e.g. [1, 2, 5]', null=True),
        ),
    ]
