# Generated by Django 5.2.17 on 2026-08-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publisher', '0005_socialpost_account_ids'),
        ('user', '0002_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='user.company'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='user.company'),
        ),
    ]
