# Generated by Django 5.2.17 on 2026-08-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publisher', '0006_socialaccount_company_socialpost_company'),
        ('user', '0002_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_post_logs', to='user.company'),
        ),
    ]
