# Generated by Django 6.1 on 2026-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publisher', '0007_socialpostlog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='app_secret_or_client_secret',
            field=models.CharField(blank=True, help_text='App Secret / Client Secret', max_length=500, null=True),
        ),
    ]
